// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-CUmz6mSJZIqKPDpWbRiiAxgakmXtdDk',
    appId: '1:394463769042:web:6fc2124ad602e3566c580b',
    messagingSenderId: '394463769042',
    projectId: 'shops-77e7a',
    authDomain: 'shops-77e7a.firebaseapp.com',
    storageBucket: 'shops-77e7a.appspot.com',
    measurementId: 'G-0TD6K7RJPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAksG1iVbxWHtf6IjfrTb_ki_HAGnTBrOE',
    appId: '1:394463769042:android:431bfb7820da43c26c580b',
    messagingSenderId: '394463769042',
    projectId: 'shops-77e7a',
    storageBucket: 'shops-77e7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdr4nZJHqT9-ABMrfqM2HZ3fj-_wZXsE',
    appId: '1:394463769042:ios:abd2a6bb3bd518d86c580b',
    messagingSenderId: '394463769042',
    projectId: 'shops-77e7a',
    storageBucket: 'shops-77e7a.appspot.com',
    iosBundleId: 'com.example.shops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdr4nZJHqT9-ABMrfqM2HZ3fj-_wZXsE',
    appId: '1:394463769042:ios:abd2a6bb3bd518d86c580b',
    messagingSenderId: '394463769042',
    projectId: 'shops-77e7a',
    storageBucket: 'shops-77e7a.appspot.com',
    iosBundleId: 'com.example.shops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-CUmz6mSJZIqKPDpWbRiiAxgakmXtdDk',
    appId: '1:394463769042:web:2c1fa2a3d7153f8e6c580b',
    messagingSenderId: '394463769042',
    projectId: 'shops-77e7a',
    authDomain: 'shops-77e7a.firebaseapp.com',
    storageBucket: 'shops-77e7a.appspot.com',
    measurementId: 'G-KFQZNTMLX8',
  );
}
